import { resolve } from "node:path"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vitest/config"

export default defineConfig({
	plugins: [react()],
	test: {
		environment: "jsdom",
		globals: true,
		setupFiles: ["./src/test/setup.ts"],
		include: ["src/**/*.{test,spec}.{ts,tsx}"],
		exclude: ["node_modules", ".next", "e2e"],
		coverage: {
			provider: "v8",
			reporter: ["text", "json", "html"],
			exclude: [
				"node_modules",
				".next",
				"src/shared/api/**", // Generated by Orval
				"src/shared/ui/**", // Generated by shadcn
				"**/*.d.ts",
				"**/*.config.*",
			],
		},
	},
	resolve: {
		alias: {
			"@app": resolve(__dirname, "./src/app"),
			"@widgets": resolve(__dirname, "./src/widgets"),
			"@features": resolve(__dirname, "./src/features"),
			"@entities": resolve(__dirname, "./src/entities"),
			"@shared": resolve(__dirname, "./src/shared"),
		},
	},
})
