version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
  exclusions:
    presets:
      - common-false-positives
    rules:
      - path: docs/
        linters:
          - all

formatters:
  enable:
    - gofmt
