version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose

formatters:
  enable:
    - gofmt

issues:
  exclude-rules:
    - path: docs/
      linters:
        - all
