/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * GocaTest API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import type { ErrorResponse, UserResponse } from "../../models"
import { customFetch } from "../../custom-fetch"

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Get the currently authenticated user's information
 * @summary Get current user
 */
export type getMeResponse = {
	data: UserResponse
	status: number
	headers: Headers
}

export const getGetMeUrl = () => {
	return `http://localhost:8080/api/v1/me`
}

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
	return customFetch<Promise<getMeResponse>>(getGetMeUrl(), {
		...options,
		method: "GET",
	})
}

export const getGetMeQueryKey = () => {
	return [`http://localhost:8080/api/v1/me`] as const
}

export const getGetMeQueryOptions = <
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey()

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) =>
		getMe({ signal, ...requestOptions })

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMe>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorResponse

export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorResponse,
>(options: {
	query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
		Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, "initialData">
	request?: SecondParameter<typeof customFetch>
}): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
		Pick<
			UndefinedInitialDataOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>,
			"initialData"
		>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get current user
 */

export function useGetMe<
	TData = Awaited<ReturnType<typeof getMe>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
	const queryOptions = getGetMeQueryOptions(options)

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData>
	}

	query.queryKey = queryOptions.queryKey

	return query
}
