/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalHandlerErrorResponse,
  InternalHandlerUpdateStatRequest,
  InternalHandlerUserResponse,
  InternalHandlerUserStatsResponse
} from '../../models';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the currently authenticated user's information
 * @summary Get current user
 */
export type getMeResponse200 = {
  data: InternalHandlerUserResponse
  status: 200
}

export type getMeResponse401 = {
  data: InternalHandlerErrorResponse
  status: 401
}
    
export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {


  

  return `http://localhost:8080/api/v1/me`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {
  
  return customFetch<getMeResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMeQueryKey = () => {
    return [
    `http://localhost:8080/api/v1/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = InternalHandlerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = InternalHandlerErrorResponse


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = InternalHandlerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = InternalHandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = InternalHandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = InternalHandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get statistics for the authenticated user
 * @summary Get user statistics
 */
export type getStatsResponse200 = {
  data: InternalHandlerUserStatsResponse
  status: 200
}

export type getStatsResponse401 = {
  data: InternalHandlerErrorResponse
  status: 401
}
    
export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse401) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = () => {


  

  return `http://localhost:8080/api/v1/stats`
}

export const getStats = async ( options?: RequestInit): Promise<getStatsResponse> => {
  
  return customFetch<getStatsResponse>(getGetStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStatsQueryKey = () => {
    return [
    `http://localhost:8080/api/v1/stats`
    ] as const;
    }

    
export const getGetStatsQueryOptions = <TData = Awaited<ReturnType<typeof getStats>>, TError = InternalHandlerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({ signal }) => getStats({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getStats>>>
export type GetStatsQueryError = InternalHandlerErrorResponse


export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = InternalHandlerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = InternalHandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = InternalHandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user statistics
 */

export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = InternalHandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Modify a stat value and broadcast the change via SSE
 * @summary Update user statistics
 */
export type postStatsResponse200 = {
  data: InternalHandlerUserStatsResponse
  status: 200
}

export type postStatsResponse400 = {
  data: InternalHandlerErrorResponse
  status: 400
}

export type postStatsResponse401 = {
  data: InternalHandlerErrorResponse
  status: 401
}
    
export type postStatsResponseSuccess = (postStatsResponse200) & {
  headers: Headers;
};
export type postStatsResponseError = (postStatsResponse400 | postStatsResponse401) & {
  headers: Headers;
};

export type postStatsResponse = (postStatsResponseSuccess | postStatsResponseError)

export const getPostStatsUrl = () => {


  

  return `http://localhost:8080/api/v1/stats`
}

export const postStats = async (internalHandlerUpdateStatRequest: InternalHandlerUpdateStatRequest, options?: RequestInit): Promise<postStatsResponse> => {
  
  return customFetch<postStatsResponse>(getPostStatsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerUpdateStatRequest,)
  }
);}




export const getPostStatsMutationOptions = <TError = InternalHandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStats>>, TError,{data: InternalHandlerUpdateStatRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postStats>>, TError,{data: InternalHandlerUpdateStatRequest}, TContext> => {

const mutationKey = ['postStats'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postStats>>, {data: InternalHandlerUpdateStatRequest}> = (props) => {
          const {data} = props ?? {};

          return  postStats(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostStatsMutationResult = NonNullable<Awaited<ReturnType<typeof postStats>>>
    export type PostStatsMutationBody = InternalHandlerUpdateStatRequest
    export type PostStatsMutationError = InternalHandlerErrorResponse

    /**
 * @summary Update user statistics
 */
export const usePostStats = <TError = InternalHandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStats>>, TError,{data: InternalHandlerUpdateStatRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postStats>>,
        TError,
        {data: InternalHandlerUpdateStatRequest},
        TContext
      > => {

      const mutationOptions = getPostStatsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    