/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HandlerErrorResponse,
  HandlerMessageResponse,
  HandlerSend2FAEnabledNotificationRequest,
  HandlerSend2FAOTPRequest,
  HandlerSendMagicLinkRequest,
  HandlerSendPasskeyAddedNotificationRequest,
  HandlerSendVerificationEmailRequest,
  HandlerSessionCreatedRequest
} from '../../models';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Notifies user that 2FA has been enabled on their account
 * @summary Send 2FA enabled notification
 */
export type postWebhooksSend2faEnabledResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type postWebhooksSend2faEnabledResponse401 = {
  data: HandlerErrorResponse
  status: 401
}

export type postWebhooksSend2faEnabledResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postWebhooksSend2faEnabledResponseSuccess = (postWebhooksSend2faEnabledResponse200) & {
  headers: Headers;
};
export type postWebhooksSend2faEnabledResponseError = (postWebhooksSend2faEnabledResponse401 | postWebhooksSend2faEnabledResponse500) & {
  headers: Headers;
};

export type postWebhooksSend2faEnabledResponse = (postWebhooksSend2faEnabledResponseSuccess | postWebhooksSend2faEnabledResponseError)

export const getPostWebhooksSend2faEnabledUrl = () => {


  

  return `http://localhost:8080/api/v1/webhooks/send-2fa-enabled`
}

export const postWebhooksSend2faEnabled = async (handlerSend2FAEnabledNotificationRequest: HandlerSend2FAEnabledNotificationRequest, options?: RequestInit): Promise<postWebhooksSend2faEnabledResponse> => {
  
  return customFetch<postWebhooksSend2faEnabledResponse>(getPostWebhooksSend2faEnabledUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerSend2FAEnabledNotificationRequest,)
  }
);}




export const getPostWebhooksSend2faEnabledMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSend2faEnabled>>, TError,{data: HandlerSend2FAEnabledNotificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSend2faEnabled>>, TError,{data: HandlerSend2FAEnabledNotificationRequest}, TContext> => {

const mutationKey = ['postWebhooksSend2faEnabled'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksSend2faEnabled>>, {data: HandlerSend2FAEnabledNotificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWebhooksSend2faEnabled(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksSend2faEnabledMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksSend2faEnabled>>>
    export type PostWebhooksSend2faEnabledMutationBody = HandlerSend2FAEnabledNotificationRequest
    export type PostWebhooksSend2faEnabledMutationError = HandlerErrorResponse

    /**
 * @summary Send 2FA enabled notification
 */
export const usePostWebhooksSend2faEnabled = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSend2faEnabled>>, TError,{data: HandlerSend2FAEnabledNotificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksSend2faEnabled>>,
        TError,
        {data: HandlerSend2FAEnabledNotificationRequest},
        TContext
      > => {

      const mutationOptions = getPostWebhooksSend2faEnabledMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Called by Better Auth to send 2FA one-time password via email
 * @summary Send 2FA OTP email
 */
export type postWebhooksSend2faOtpResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type postWebhooksSend2faOtpResponse401 = {
  data: HandlerErrorResponse
  status: 401
}

export type postWebhooksSend2faOtpResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postWebhooksSend2faOtpResponseSuccess = (postWebhooksSend2faOtpResponse200) & {
  headers: Headers;
};
export type postWebhooksSend2faOtpResponseError = (postWebhooksSend2faOtpResponse401 | postWebhooksSend2faOtpResponse500) & {
  headers: Headers;
};

export type postWebhooksSend2faOtpResponse = (postWebhooksSend2faOtpResponseSuccess | postWebhooksSend2faOtpResponseError)

export const getPostWebhooksSend2faOtpUrl = () => {


  

  return `http://localhost:8080/api/v1/webhooks/send-2fa-otp`
}

export const postWebhooksSend2faOtp = async (handlerSend2FAOTPRequest: HandlerSend2FAOTPRequest, options?: RequestInit): Promise<postWebhooksSend2faOtpResponse> => {
  
  return customFetch<postWebhooksSend2faOtpResponse>(getPostWebhooksSend2faOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerSend2FAOTPRequest,)
  }
);}




export const getPostWebhooksSend2faOtpMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSend2faOtp>>, TError,{data: HandlerSend2FAOTPRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSend2faOtp>>, TError,{data: HandlerSend2FAOTPRequest}, TContext> => {

const mutationKey = ['postWebhooksSend2faOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksSend2faOtp>>, {data: HandlerSend2FAOTPRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWebhooksSend2faOtp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksSend2faOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksSend2faOtp>>>
    export type PostWebhooksSend2faOtpMutationBody = HandlerSend2FAOTPRequest
    export type PostWebhooksSend2faOtpMutationError = HandlerErrorResponse

    /**
 * @summary Send 2FA OTP email
 */
export const usePostWebhooksSend2faOtp = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSend2faOtp>>, TError,{data: HandlerSend2FAOTPRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksSend2faOtp>>,
        TError,
        {data: HandlerSend2FAOTPRequest},
        TContext
      > => {

      const mutationOptions = getPostWebhooksSend2faOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Called by Better Auth to send magic link login email
 * @summary Send magic link email
 */
export type postWebhooksSendMagicLinkResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type postWebhooksSendMagicLinkResponse401 = {
  data: HandlerErrorResponse
  status: 401
}

export type postWebhooksSendMagicLinkResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postWebhooksSendMagicLinkResponseSuccess = (postWebhooksSendMagicLinkResponse200) & {
  headers: Headers;
};
export type postWebhooksSendMagicLinkResponseError = (postWebhooksSendMagicLinkResponse401 | postWebhooksSendMagicLinkResponse500) & {
  headers: Headers;
};

export type postWebhooksSendMagicLinkResponse = (postWebhooksSendMagicLinkResponseSuccess | postWebhooksSendMagicLinkResponseError)

export const getPostWebhooksSendMagicLinkUrl = () => {


  

  return `http://localhost:8080/api/v1/webhooks/send-magic-link`
}

export const postWebhooksSendMagicLink = async (handlerSendMagicLinkRequest: HandlerSendMagicLinkRequest, options?: RequestInit): Promise<postWebhooksSendMagicLinkResponse> => {
  
  return customFetch<postWebhooksSendMagicLinkResponse>(getPostWebhooksSendMagicLinkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerSendMagicLinkRequest,)
  }
);}




export const getPostWebhooksSendMagicLinkMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendMagicLink>>, TError,{data: HandlerSendMagicLinkRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendMagicLink>>, TError,{data: HandlerSendMagicLinkRequest}, TContext> => {

const mutationKey = ['postWebhooksSendMagicLink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksSendMagicLink>>, {data: HandlerSendMagicLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWebhooksSendMagicLink(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksSendMagicLinkMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksSendMagicLink>>>
    export type PostWebhooksSendMagicLinkMutationBody = HandlerSendMagicLinkRequest
    export type PostWebhooksSendMagicLinkMutationError = HandlerErrorResponse

    /**
 * @summary Send magic link email
 */
export const usePostWebhooksSendMagicLink = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendMagicLink>>, TError,{data: HandlerSendMagicLinkRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksSendMagicLink>>,
        TError,
        {data: HandlerSendMagicLinkRequest},
        TContext
      > => {

      const mutationOptions = getPostWebhooksSendMagicLinkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Notifies user that a new passkey has been added to their account
 * @summary Send passkey added notification
 */
export type postWebhooksSendPasskeyAddedResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type postWebhooksSendPasskeyAddedResponse401 = {
  data: HandlerErrorResponse
  status: 401
}

export type postWebhooksSendPasskeyAddedResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postWebhooksSendPasskeyAddedResponseSuccess = (postWebhooksSendPasskeyAddedResponse200) & {
  headers: Headers;
};
export type postWebhooksSendPasskeyAddedResponseError = (postWebhooksSendPasskeyAddedResponse401 | postWebhooksSendPasskeyAddedResponse500) & {
  headers: Headers;
};

export type postWebhooksSendPasskeyAddedResponse = (postWebhooksSendPasskeyAddedResponseSuccess | postWebhooksSendPasskeyAddedResponseError)

export const getPostWebhooksSendPasskeyAddedUrl = () => {


  

  return `http://localhost:8080/api/v1/webhooks/send-passkey-added`
}

export const postWebhooksSendPasskeyAdded = async (handlerSendPasskeyAddedNotificationRequest: HandlerSendPasskeyAddedNotificationRequest, options?: RequestInit): Promise<postWebhooksSendPasskeyAddedResponse> => {
  
  return customFetch<postWebhooksSendPasskeyAddedResponse>(getPostWebhooksSendPasskeyAddedUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerSendPasskeyAddedNotificationRequest,)
  }
);}




export const getPostWebhooksSendPasskeyAddedMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendPasskeyAdded>>, TError,{data: HandlerSendPasskeyAddedNotificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendPasskeyAdded>>, TError,{data: HandlerSendPasskeyAddedNotificationRequest}, TContext> => {

const mutationKey = ['postWebhooksSendPasskeyAdded'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksSendPasskeyAdded>>, {data: HandlerSendPasskeyAddedNotificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWebhooksSendPasskeyAdded(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksSendPasskeyAddedMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksSendPasskeyAdded>>>
    export type PostWebhooksSendPasskeyAddedMutationBody = HandlerSendPasskeyAddedNotificationRequest
    export type PostWebhooksSendPasskeyAddedMutationError = HandlerErrorResponse

    /**
 * @summary Send passkey added notification
 */
export const usePostWebhooksSendPasskeyAdded = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendPasskeyAdded>>, TError,{data: HandlerSendPasskeyAddedNotificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksSendPasskeyAdded>>,
        TError,
        {data: HandlerSendPasskeyAddedNotificationRequest},
        TContext
      > => {

      const mutationOptions = getPostWebhooksSendPasskeyAddedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Called by Better Auth to send email verification link
 * @summary Send verification email
 */
export type postWebhooksSendVerificationEmailResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type postWebhooksSendVerificationEmailResponse401 = {
  data: HandlerErrorResponse
  status: 401
}

export type postWebhooksSendVerificationEmailResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postWebhooksSendVerificationEmailResponseSuccess = (postWebhooksSendVerificationEmailResponse200) & {
  headers: Headers;
};
export type postWebhooksSendVerificationEmailResponseError = (postWebhooksSendVerificationEmailResponse401 | postWebhooksSendVerificationEmailResponse500) & {
  headers: Headers;
};

export type postWebhooksSendVerificationEmailResponse = (postWebhooksSendVerificationEmailResponseSuccess | postWebhooksSendVerificationEmailResponseError)

export const getPostWebhooksSendVerificationEmailUrl = () => {


  

  return `http://localhost:8080/api/v1/webhooks/send-verification-email`
}

export const postWebhooksSendVerificationEmail = async (handlerSendVerificationEmailRequest: HandlerSendVerificationEmailRequest, options?: RequestInit): Promise<postWebhooksSendVerificationEmailResponse> => {
  
  return customFetch<postWebhooksSendVerificationEmailResponse>(getPostWebhooksSendVerificationEmailUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerSendVerificationEmailRequest,)
  }
);}




export const getPostWebhooksSendVerificationEmailMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendVerificationEmail>>, TError,{data: HandlerSendVerificationEmailRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendVerificationEmail>>, TError,{data: HandlerSendVerificationEmailRequest}, TContext> => {

const mutationKey = ['postWebhooksSendVerificationEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksSendVerificationEmail>>, {data: HandlerSendVerificationEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWebhooksSendVerificationEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksSendVerificationEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksSendVerificationEmail>>>
    export type PostWebhooksSendVerificationEmailMutationBody = HandlerSendVerificationEmailRequest
    export type PostWebhooksSendVerificationEmailMutationError = HandlerErrorResponse

    /**
 * @summary Send verification email
 */
export const usePostWebhooksSendVerificationEmail = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSendVerificationEmail>>, TError,{data: HandlerSendVerificationEmailRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksSendVerificationEmail>>,
        TError,
        {data: HandlerSendVerificationEmailRequest},
        TContext
      > => {

      const mutationOptions = getPostWebhooksSendVerificationEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Called by Better Auth when a new session is created. Sends notification email for new devices.
 * @summary Handle new session webhook
 */
export type postWebhooksSessionCreatedResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type postWebhooksSessionCreatedResponse401 = {
  data: HandlerErrorResponse
  status: 401
}

export type postWebhooksSessionCreatedResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postWebhooksSessionCreatedResponseSuccess = (postWebhooksSessionCreatedResponse200) & {
  headers: Headers;
};
export type postWebhooksSessionCreatedResponseError = (postWebhooksSessionCreatedResponse401 | postWebhooksSessionCreatedResponse500) & {
  headers: Headers;
};

export type postWebhooksSessionCreatedResponse = (postWebhooksSessionCreatedResponseSuccess | postWebhooksSessionCreatedResponseError)

export const getPostWebhooksSessionCreatedUrl = () => {


  

  return `http://localhost:8080/api/v1/webhooks/session-created`
}

export const postWebhooksSessionCreated = async (handlerSessionCreatedRequest: HandlerSessionCreatedRequest, options?: RequestInit): Promise<postWebhooksSessionCreatedResponse> => {
  
  return customFetch<postWebhooksSessionCreatedResponse>(getPostWebhooksSessionCreatedUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerSessionCreatedRequest,)
  }
);}




export const getPostWebhooksSessionCreatedMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSessionCreated>>, TError,{data: HandlerSessionCreatedRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSessionCreated>>, TError,{data: HandlerSessionCreatedRequest}, TContext> => {

const mutationKey = ['postWebhooksSessionCreated'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksSessionCreated>>, {data: HandlerSessionCreatedRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWebhooksSessionCreated(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksSessionCreatedMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksSessionCreated>>>
    export type PostWebhooksSessionCreatedMutationBody = HandlerSessionCreatedRequest
    export type PostWebhooksSessionCreatedMutationError = HandlerErrorResponse

    /**
 * @summary Handle new session webhook
 */
export const usePostWebhooksSessionCreated = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksSessionCreated>>, TError,{data: HandlerSessionCreatedRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksSessionCreated>>,
        TError,
        {data: HandlerSessionCreatedRequest},
        TContext
      > => {

      const mutationOptions = getPostWebhooksSessionCreatedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    