/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * GocaTest API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */

export * from "./errorResponse";
export * from "./messageResponse";
export * from "./userResponse";
export * from './internalHandlerErrorResponse';
export * from './internalHandlerMessageResponse';
export * from './internalHandlerUpdateStatRequest';
export * from './internalHandlerUserResponse';
export * from './internalHandlerUserStatsResponse';