/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * GocaTest API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import type { MessageResponse } from "../../models"
import { customFetch } from "../../custom-fetch"

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Returns a hello message, no auth required
 * @summary Public hello endpoint
 */
export type getHelloResponse = {
	data: MessageResponse
	status: number
	headers: Headers
}

export const getGetHelloUrl = () => {
	return `http://localhost:8080/api/v1/hello`
}

export const getHello = async (options?: RequestInit): Promise<getHelloResponse> => {
	return customFetch<Promise<getHelloResponse>>(getGetHelloUrl(), {
		...options,
		method: "GET",
	})
}

export const getGetHelloQueryKey = () => {
	return [`http://localhost:8080/api/v1/hello`] as const
}

export const getGetHelloQueryOptions = <
	TData = Awaited<ReturnType<typeof getHello>>,
	TError = unknown,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetHelloQueryKey()

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getHello>>> = ({ signal }) =>
		getHello({ signal, ...requestOptions })

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getHello>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof getHello>>>
export type GetHelloQueryError = unknown

export function useGetHello<
	TData = Awaited<ReturnType<typeof getHello>>,
	TError = unknown,
>(options: {
	query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>> &
		Pick<
			DefinedInitialDataOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>,
			"initialData"
		>
	request?: SecondParameter<typeof customFetch>
}): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetHello<
	TData = Awaited<ReturnType<typeof getHello>>,
	TError = unknown,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>> &
		Pick<
			UndefinedInitialDataOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>,
			"initialData"
		>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetHello<
	TData = Awaited<ReturnType<typeof getHello>>,
	TError = unknown,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Public hello endpoint
 */

export function useGetHello<
	TData = Awaited<ReturnType<typeof getHello>>,
	TError = unknown,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
	const queryOptions = getGetHelloQueryOptions(options)

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData>
	}

	query.queryKey = queryOptions.queryKey

	return query
}
