/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */

export interface AiworkflowsInterfacesHttpRepoSummaryListItem {
  fileCount?: number;
  id?: number;
  repoUrl?: string;
  startedAt?: string;
  status?: string;
  updatedAt?: string;
}
