/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import type { AiworkflowsInterfacesHttpFileSummaryDTO } from './aiworkflowsInterfacesHttpFileSummaryDTO';
import type { AiworkflowsInterfacesHttpRepoSummaryResponseStepDurations } from './aiworkflowsInterfacesHttpRepoSummaryResponseStepDurations';

export interface AiworkflowsInterfacesHttpRepoSummaryResponse {
  completedAt?: string;
  failReason?: string;
  files?: AiworkflowsInterfacesHttpFileSummaryDTO[];
  id?: number;
  repoUrl?: string;
  startedAt?: string;
  status?: string;
  stepDurations?: AiworkflowsInterfacesHttpRepoSummaryResponseStepDurations;
  summary?: string;
}
