/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import type { AiworkflowsInterfacesHttpRepoSummaryListItem } from './aiworkflowsInterfacesHttpRepoSummaryListItem';

export interface AiworkflowsInterfacesHttpRepoSummaryListResponse {
  items?: AiworkflowsInterfacesHttpRepoSummaryListItem[];
}
