/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * GocaTest API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */

export interface ErrorResponse {
	error?: string
}
