/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */

export interface HandlerStartExportRequest {
  /** "stats", "activity", or "all" */
  dataType?: string;
  /** "csv" or "json" */
  format?: string;
}
