/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HandlerErrorResponse,
  HandlerStartExportRequest,
  HandlerStartExportResponse
} from '../../models';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Downloads the exported file by download ID
 * @summary Download a completed export
 */
export type getExportDownloadIdResponse200 = {
  data: Blob
  status: 200
}

export type getExportDownloadIdResponse404 = {
  data: HandlerErrorResponse
  status: 404
}
    
export type getExportDownloadIdResponseSuccess = (getExportDownloadIdResponse200) & {
  headers: Headers;
};
export type getExportDownloadIdResponseError = (getExportDownloadIdResponse404) & {
  headers: Headers;
};

export type getExportDownloadIdResponse = (getExportDownloadIdResponseSuccess | getExportDownloadIdResponseError)

export const getGetExportDownloadIdUrl = (id: string,) => {


  

  return `http://localhost:8080/api/v1/export/download/${id}`
}

export const getExportDownloadId = async (id: string, options?: RequestInit): Promise<getExportDownloadIdResponse> => {
  
  return customFetch<getExportDownloadIdResponse>(getGetExportDownloadIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetExportDownloadIdQueryKey = (id?: string,) => {
    return [
    `http://localhost:8080/api/v1/export/download/${id}`
    ] as const;
    }

    
export const getGetExportDownloadIdQueryOptions = <TData = Awaited<ReturnType<typeof getExportDownloadId>>, TError = HandlerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExportDownloadId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExportDownloadIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExportDownloadId>>> = ({ signal }) => getExportDownloadId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExportDownloadId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExportDownloadIdQueryResult = NonNullable<Awaited<ReturnType<typeof getExportDownloadId>>>
export type GetExportDownloadIdQueryError = HandlerErrorResponse


export function useGetExportDownloadId<TData = Awaited<ReturnType<typeof getExportDownloadId>>, TError = HandlerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExportDownloadId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExportDownloadId>>,
          TError,
          Awaited<ReturnType<typeof getExportDownloadId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExportDownloadId<TData = Awaited<ReturnType<typeof getExportDownloadId>>, TError = HandlerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExportDownloadId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExportDownloadId>>,
          TError,
          Awaited<ReturnType<typeof getExportDownloadId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExportDownloadId<TData = Awaited<ReturnType<typeof getExportDownloadId>>, TError = HandlerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExportDownloadId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download a completed export
 */

export function useGetExportDownloadId<TData = Awaited<ReturnType<typeof getExportDownloadId>>, TError = HandlerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExportDownloadId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExportDownloadIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Starts a background job to export user data
 * @summary Start a data export job
 */
export type postExportStartResponse200 = {
  data: HandlerStartExportResponse
  status: 200
}

export type postExportStartResponse400 = {
  data: HandlerErrorResponse
  status: 400
}

export type postExportStartResponse500 = {
  data: HandlerErrorResponse
  status: 500
}
    
export type postExportStartResponseSuccess = (postExportStartResponse200) & {
  headers: Headers;
};
export type postExportStartResponseError = (postExportStartResponse400 | postExportStartResponse500) & {
  headers: Headers;
};

export type postExportStartResponse = (postExportStartResponseSuccess | postExportStartResponseError)

export const getPostExportStartUrl = () => {


  

  return `http://localhost:8080/api/v1/export/start`
}

export const postExportStart = async (handlerStartExportRequest: HandlerStartExportRequest, options?: RequestInit): Promise<postExportStartResponse> => {
  
  return customFetch<postExportStartResponse>(getPostExportStartUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlerStartExportRequest,)
  }
);}




export const getPostExportStartMutationOptions = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postExportStart>>, TError,{data: HandlerStartExportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postExportStart>>, TError,{data: HandlerStartExportRequest}, TContext> => {

const mutationKey = ['postExportStart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postExportStart>>, {data: HandlerStartExportRequest}> = (props) => {
          const {data} = props ?? {};

          return  postExportStart(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostExportStartMutationResult = NonNullable<Awaited<ReturnType<typeof postExportStart>>>
    export type PostExportStartMutationBody = HandlerStartExportRequest
    export type PostExportStartMutationError = HandlerErrorResponse

    /**
 * @summary Start a data export job
 */
export const usePostExportStart = <TError = HandlerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postExportStart>>, TError,{data: HandlerStartExportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postExportStart>>,
        TError,
        {data: HandlerStartExportRequest},
        TContext
      > => {

      const mutationOptions = getPostExportStartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    