/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HandlerErrorResponse,
  HandlerMessageResponse
} from '../../models';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a personalized hello message for authenticated users
 * @summary Protected hello endpoint
 */
export type getProtectedHelloResponse200 = {
  data: HandlerMessageResponse
  status: 200
}

export type getProtectedHelloResponse401 = {
  data: HandlerErrorResponse
  status: 401
}
    
export type getProtectedHelloResponseSuccess = (getProtectedHelloResponse200) & {
  headers: Headers;
};
export type getProtectedHelloResponseError = (getProtectedHelloResponse401) & {
  headers: Headers;
};

export type getProtectedHelloResponse = (getProtectedHelloResponseSuccess | getProtectedHelloResponseError)

export const getGetProtectedHelloUrl = () => {


  

  return `http://localhost:8080/api/v1/protected/hello`
}

export const getProtectedHello = async ( options?: RequestInit): Promise<getProtectedHelloResponse> => {
  
  return customFetch<getProtectedHelloResponse>(getGetProtectedHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetProtectedHelloQueryKey = () => {
    return [
    `http://localhost:8080/api/v1/protected/hello`
    ] as const;
    }

    
export const getGetProtectedHelloQueryOptions = <TData = Awaited<ReturnType<typeof getProtectedHello>>, TError = HandlerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProtectedHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProtectedHello>>> = ({ signal }) => getProtectedHello({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProtectedHelloQueryResult = NonNullable<Awaited<ReturnType<typeof getProtectedHello>>>
export type GetProtectedHelloQueryError = HandlerErrorResponse


export function useGetProtectedHello<TData = Awaited<ReturnType<typeof getProtectedHello>>, TError = HandlerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProtectedHello>>,
          TError,
          Awaited<ReturnType<typeof getProtectedHello>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProtectedHello<TData = Awaited<ReturnType<typeof getProtectedHello>>, TError = HandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProtectedHello>>,
          TError,
          Awaited<ReturnType<typeof getProtectedHello>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProtectedHello<TData = Awaited<ReturnType<typeof getProtectedHello>>, TError = HandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Protected hello endpoint
 */

export function useGetProtectedHello<TData = Awaited<ReturnType<typeof getProtectedHello>>, TError = HandlerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProtectedHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




