/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * GocaTest API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import type { ErrorResponse, MessageResponse } from "../../models"
import { customFetch } from "../../custom-fetch"

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Returns a personalized hello message for authenticated users
 * @summary Protected hello endpoint
 */
export type getProtectedHelloResponse = {
	data: MessageResponse
	status: number
	headers: Headers
}

export const getGetProtectedHelloUrl = () => {
	return `http://localhost:8080/api/v1/protected/hello`
}

export const getProtectedHello = async (
	options?: RequestInit,
): Promise<getProtectedHelloResponse> => {
	return customFetch<Promise<getProtectedHelloResponse>>(getGetProtectedHelloUrl(), {
		...options,
		method: "GET",
	})
}

export const getGetProtectedHelloQueryKey = () => {
	return [`http://localhost:8080/api/v1/protected/hello`] as const
}

export const getGetProtectedHelloQueryOptions = <
	TData = Awaited<ReturnType<typeof getProtectedHello>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetProtectedHelloQueryKey()

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getProtectedHello>>> = ({ signal }) =>
		getProtectedHello({ signal, ...requestOptions })

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getProtectedHello>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetProtectedHelloQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProtectedHello>>
>
export type GetProtectedHelloQueryError = ErrorResponse

export function useGetProtectedHello<
	TData = Awaited<ReturnType<typeof getProtectedHello>>,
	TError = ErrorResponse,
>(options: {
	query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>> &
		Pick<
			DefinedInitialDataOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>,
			"initialData"
		>
	request?: SecondParameter<typeof customFetch>
}): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProtectedHello<
	TData = Awaited<ReturnType<typeof getProtectedHello>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>> &
		Pick<
			UndefinedInitialDataOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>,
			"initialData"
		>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProtectedHello<
	TData = Awaited<ReturnType<typeof getProtectedHello>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Protected hello endpoint
 */

export function useGetProtectedHello<
	TData = Awaited<ReturnType<typeof getProtectedHello>>,
	TError = ErrorResponse,
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtectedHello>>, TError, TData>>
	request?: SecondParameter<typeof customFetch>
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
	const queryOptions = getGetProtectedHelloQueryOptions(options)

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData>
	}

	query.queryKey = queryOptions.queryKey

	return query
}
