/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Next-Go-PG API
 * Go Clean Architecture API with Better Auth integration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AiworkflowsInterfacesHttpErrorResponse,
  AiworkflowsInterfacesHttpRepoSummaryListResponse,
  AiworkflowsInterfacesHttpRepoSummaryResponse,
  AiworkflowsInterfacesHttpSummarizeRepoRequest,
  AiworkflowsInterfacesHttpSummarizeRepoResponse
} from '../../models';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns up to 50 of the authenticated user's runs, newest first. Used by the AI page to show a history of past runs.
 * @summary List the user's recent repository summaries
 */
export type getAiSummariesResponse200 = {
  data: AiworkflowsInterfacesHttpRepoSummaryListResponse
  status: 200
}

export type getAiSummariesResponse401 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 401
}

export type getAiSummariesResponse503 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 503
}
    
export type getAiSummariesResponseSuccess = (getAiSummariesResponse200) & {
  headers: Headers;
};
export type getAiSummariesResponseError = (getAiSummariesResponse401 | getAiSummariesResponse503) & {
  headers: Headers;
};

export type getAiSummariesResponse = (getAiSummariesResponseSuccess | getAiSummariesResponseError)

export const getGetAiSummariesUrl = () => {


  

  return `http://localhost:8080/api/v1/ai/summaries`
}

export const getAiSummaries = async ( options?: RequestInit): Promise<getAiSummariesResponse> => {
  
  return customFetch<getAiSummariesResponse>(getGetAiSummariesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAiSummariesQueryKey = () => {
    return [
    `http://localhost:8080/api/v1/ai/summaries`
    ] as const;
    }

    
export const getGetAiSummariesQueryOptions = <TData = Awaited<ReturnType<typeof getAiSummaries>>, TError = AiworkflowsInterfacesHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummaries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAiSummariesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiSummaries>>> = ({ signal }) => getAiSummaries({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAiSummaries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAiSummariesQueryResult = NonNullable<Awaited<ReturnType<typeof getAiSummaries>>>
export type GetAiSummariesQueryError = AiworkflowsInterfacesHttpErrorResponse


export function useGetAiSummaries<TData = Awaited<ReturnType<typeof getAiSummaries>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummaries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiSummaries>>,
          TError,
          Awaited<ReturnType<typeof getAiSummaries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAiSummaries<TData = Awaited<ReturnType<typeof getAiSummaries>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummaries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiSummaries>>,
          TError,
          Awaited<ReturnType<typeof getAiSummaries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAiSummaries<TData = Awaited<ReturnType<typeof getAiSummaries>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummaries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the user's recent repository summaries
 */

export function useGetAiSummaries<TData = Awaited<ReturnType<typeof getAiSummaries>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummaries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAiSummariesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the stored summary for a run owned by the authenticated user. Cross-user reads return 404 to avoid leaking existence.
 * @summary Get a repository summarization result
 */
export type getAiSummariesIdResponse200 = {
  data: AiworkflowsInterfacesHttpRepoSummaryResponse
  status: 200
}

export type getAiSummariesIdResponse401 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 401
}

export type getAiSummariesIdResponse404 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 404
}

export type getAiSummariesIdResponse503 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 503
}
    
export type getAiSummariesIdResponseSuccess = (getAiSummariesIdResponse200) & {
  headers: Headers;
};
export type getAiSummariesIdResponseError = (getAiSummariesIdResponse401 | getAiSummariesIdResponse404 | getAiSummariesIdResponse503) & {
  headers: Headers;
};

export type getAiSummariesIdResponse = (getAiSummariesIdResponseSuccess | getAiSummariesIdResponseError)

export const getGetAiSummariesIdUrl = (id: number,) => {


  

  return `http://localhost:8080/api/v1/ai/summaries/${id}`
}

export const getAiSummariesId = async (id: number, options?: RequestInit): Promise<getAiSummariesIdResponse> => {
  
  return customFetch<getAiSummariesIdResponse>(getGetAiSummariesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAiSummariesIdQueryKey = (id?: number,) => {
    return [
    `http://localhost:8080/api/v1/ai/summaries/${id}`
    ] as const;
    }

    
export const getGetAiSummariesIdQueryOptions = <TData = Awaited<ReturnType<typeof getAiSummariesId>>, TError = AiworkflowsInterfacesHttpErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummariesId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAiSummariesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiSummariesId>>> = ({ signal }) => getAiSummariesId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAiSummariesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAiSummariesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAiSummariesId>>>
export type GetAiSummariesIdQueryError = AiworkflowsInterfacesHttpErrorResponse


export function useGetAiSummariesId<TData = Awaited<ReturnType<typeof getAiSummariesId>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummariesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiSummariesId>>,
          TError,
          Awaited<ReturnType<typeof getAiSummariesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAiSummariesId<TData = Awaited<ReturnType<typeof getAiSummariesId>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummariesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAiSummariesId>>,
          TError,
          Awaited<ReturnType<typeof getAiSummariesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAiSummariesId<TData = Awaited<ReturnType<typeof getAiSummariesId>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummariesId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a repository summarization result
 */

export function useGetAiSummariesId<TData = Awaited<ReturnType<typeof getAiSummariesId>>, TError = AiworkflowsInterfacesHttpErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiSummariesId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAiSummariesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Enqueues a Hatchet workflow that clones the repository, summarises individual files via Ollama, and produces a repo-level summary.
 * @summary Trigger a repository summarization workflow
 */
export type postAiSummarizeRepoResponse202 = {
  data: AiworkflowsInterfacesHttpSummarizeRepoResponse
  status: 202
}

export type postAiSummarizeRepoResponse400 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 400
}

export type postAiSummarizeRepoResponse401 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 401
}

export type postAiSummarizeRepoResponse503 = {
  data: AiworkflowsInterfacesHttpErrorResponse
  status: 503
}
    
export type postAiSummarizeRepoResponseSuccess = (postAiSummarizeRepoResponse202) & {
  headers: Headers;
};
export type postAiSummarizeRepoResponseError = (postAiSummarizeRepoResponse400 | postAiSummarizeRepoResponse401 | postAiSummarizeRepoResponse503) & {
  headers: Headers;
};

export type postAiSummarizeRepoResponse = (postAiSummarizeRepoResponseSuccess | postAiSummarizeRepoResponseError)

export const getPostAiSummarizeRepoUrl = () => {


  

  return `http://localhost:8080/api/v1/ai/summarize-repo`
}

export const postAiSummarizeRepo = async (aiworkflowsInterfacesHttpSummarizeRepoRequest: AiworkflowsInterfacesHttpSummarizeRepoRequest, options?: RequestInit): Promise<postAiSummarizeRepoResponse> => {
  
  return customFetch<postAiSummarizeRepoResponse>(getPostAiSummarizeRepoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      aiworkflowsInterfacesHttpSummarizeRepoRequest,)
  }
);}




export const getPostAiSummarizeRepoMutationOptions = <TError = AiworkflowsInterfacesHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAiSummarizeRepo>>, TError,{data: AiworkflowsInterfacesHttpSummarizeRepoRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAiSummarizeRepo>>, TError,{data: AiworkflowsInterfacesHttpSummarizeRepoRequest}, TContext> => {

const mutationKey = ['postAiSummarizeRepo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAiSummarizeRepo>>, {data: AiworkflowsInterfacesHttpSummarizeRepoRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAiSummarizeRepo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAiSummarizeRepoMutationResult = NonNullable<Awaited<ReturnType<typeof postAiSummarizeRepo>>>
    export type PostAiSummarizeRepoMutationBody = AiworkflowsInterfacesHttpSummarizeRepoRequest
    export type PostAiSummarizeRepoMutationError = AiworkflowsInterfacesHttpErrorResponse

    /**
 * @summary Trigger a repository summarization workflow
 */
export const usePostAiSummarizeRepo = <TError = AiworkflowsInterfacesHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAiSummarizeRepo>>, TError,{data: AiworkflowsInterfacesHttpSummarizeRepoRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAiSummarizeRepo>>,
        TError,
        {data: AiworkflowsInterfacesHttpSummarizeRepoRequest},
        TContext
      > => {

      const mutationOptions = getPostAiSummarizeRepoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    